#!/bin/bash
# Restrict kids computer access to specific hours and total time.
# By: Michael Groves - grover66_at_gmail_dot_com

#variables
#LANG="en_US.UTF-8" #unremark to change preferred language.
basedir="/usr/local/kidtimer"
configdir="/etc/kidtimer"
SHUTDOWN_BASE="/var/run/kidtimer.shutdown"
KILLALL_BASE="/var/run/kidtimer.killall"
Cdate=`/bin/date +%Y-%m-%d`
TUI=0
HOUR=`/bin/date +%H`
DOW=`/bin/date +%u`
WEEKEND="no"
[ "$DOW" == "6" ] && WEEKEND="yes"
[ "$DOW" == "7" ] && WEEKEND="yes"
[ ! -e $configdir/kid.list ] && touch $configdir/kid.list
[ ! -e $basedir/locale/$LANG ] && LANG="en_US.UTF-8"

#arguments
[ $# -eq 0 ] && TUI=1
[ $# -eq 1 ] && COMMAND=$1
[ $# -eq 2 ] && COMMAND=$1 && KID=$2
[ $# -eq 3 ] && COMMAND=$1 && KID=$2 && Time=$3

################# Subroutines ##################
################################################

#
#  Decriment ttl (time to live) in mins and return current time left
#
set_ttl () {
    local kid=$1
    local min=$2

    #more time
    local mtime=`date +%s`
    local mfile=$(expr $mtime / 10000)
    if [ -e /tmp/$mfile ]; then
        /bin/rm -f /tmp/$mfile
        reset_time $kid
        return
    fi


    # Normal mode is to decriment a minute
    if [ -e $basedir/time/$kid.ttl ]; then
        min=`/bin/cat $basedir/time/$kid.ttl`
        if [ $min -le 0 ]; then
            min=0
        else
            min=$((min - 1))
        fi

        echo $min > $basedir/time/$kid.ttl

    #first time for a user, create file, and set default ttl
    else
        get_ttl_time $kid > $basedir/time/$kid.ttl
        min=`/bin/cat $basedir/time/$kid.ttl`
    fi

    return 0
}

get_info () {
    echo "kidtimer info"
    echo "---------------------------------------------"
    /bin/date
    echo "---"
    echo "find /usr/local/kidtimer/ -print | sort"
    /usr/bin/find /usr/local/kidtimer/ -print | /usr/bin/sort
    echo "---"
    echo "cat $configdir/kid.list"
    /bin/cat $configdir/kid.list
    echo "---"
    echo "passwd -S -a"
    /usr/bin/passwd -S -a
    echo "---"
    echo "cat /usr/local/kidtimer/schedule/*"
    /bin/cat /usr/local/kidtimer/schedule/*
    echo "---"
    echo "cat /usr/local/kidtimer/time/*"
    /bin/cat /usr/local/kidtimer/time/*
    echo "---"
    echo "cat /etc/cron.d/kidtimer"
    /bin/cat /etc/cron.d/kidtimer
    echo "---"
    echo "apt-cache showpkg kidtimer"
    /usr/bin/apt-cache showpkg kidtimer
    echo "---"
    echo "cat /etc/lsb-release"
    /bin/cat /etc/lsb-release
    echo "---"
    echo "uname -a"
    /bin/uname -a
    echo "---"
    echo "env"
    /usr/bin/env
    echo
}


go_check () {
    local kid
    local min
    local allowed

    for kid in `/bin/cat $configdir/kid.list | sort -u`; do

        # New day means we reset the ttl
        /usr/bin/stat -c %y $basedir/time/$kid.ttl | /bin/grep -q $Cdate
        if [ ! $? -eq 0 ]; then
            reset_time $kid
            return
        fi

        # This method ( /usr/bin/users ) to determine who is logged in is a kludge.
        # It ignores locked screens (screensaver active) and switched user states.
        # change ttl for logged in user and return remaining time
        /usr/bin/users | /bin/grep -q $kid
        if [ $? -eq 0 ]; then

            set_ttl $kid $min

            # Get current time left
            [ -e $basedir/time/$kid.ttl ] && min=`/bin/cat $basedir/time/$kid.ttl`

            # Are they allowed to use computer during this hour
            hourlyCheck $kid $allowed

            # Determine if allowed based on schedule
            allowed=1
            if [ -e $basedir/schedule/$kid ]; then
                local schedule_result
                [ "$WEEKEND" == "no" ] && schedule_result=`/bin/grep ^$HOUR $basedir/schedule/$kid | /usr/bin/awk '{ print $2 }'`
                [ "$WEEKEND" == "yes" ] && schedule_result=`/bin/grep ^$HOUR $basedir/schedule/$kid | /usr/bin/awk '{ print $3 }'`
                [ "$schedule_result" != "y" ] && allowed=0
            fi

            # check time, lock account, and start stutdown procedure, queue up jobs
            if [ $min -le 5 ] || [ $allowed -eq 0 ]; then
                go_logout_async $kid
            fi
        fi
    done
}


get_ttl_time () {
    [ "$WEEKEND" == "no" ] && /bin/cat $basedir/schedule/$1 | /bin/grep ^MAX | /usr/bin/awk '{ print $2 }'
    [ "$WEEKEND" == "yes" ] && /bin/cat $basedir/schedule/$1 | /bin/grep ^MAX | /usr/bin/awk '{ print $3 }'
}


go_lock_account () {
    local user=$1
    /usr/sbin/usermod --expiredate 1 ${user}
}

go_unlock_account () {
    local user=$1
    /usr/sbin/usermod --expiredate "" ${user}
}

go_clean_jobs () {
    local user=$1
    local job
    for job in `/usr/bin/atq | /usr/bin/awk '{ print $1 }' | /usr/bin/sort`; do
        /usr/bin/at -d $job
    #        /usr/bin/at -c $job | /bin/grep -q "bash.$user"
    #        [ $? -eq 0 ] && /usr/bin/at -d $job
    done
    [ -e ${SHUTDOWN_BASE}.${user} ] && /bin/rm -rf ${SHUTDOWN_BASE}.${user}
    [ -e /tmp/kidtimer.send1.bash.${user} ] && /bin/rm -rf /tmp/kidtimer.send1.bash.${user}
    [ -e /tmp/kidtimer.send2.bash.${user} ] && /bin/rm -rf /tmp/kidtimer.send2.bash.${user}
    [ -e /tmp/kidtimer.send3.bash.${user} ] && /bin/rm -rf /tmp/kidtimer.send3.bash.${user}
    [ -e /tmp/kidtimer.send4.bash.${user} ] && /bin/rm -rf /tmp/kidtimer.send4.bash.${user}
    [ -e /tmp/kidtimer.send5.bash.${user} ] && /bin/rm -rf /tmp/kidtimer.send5.bash.${user}
    [ -e ${KILLALL_BASE}.${user} ] && /bin/rm -rf ${KILLALL_BASE}.${user}
    go_unlock_account ${user}
}


# From command line only.... check now handles this autmoatically... don't need
#   to run from cron
#
# runs once per day and resets ttl back for kid
# %%% what happens if machine is suspended and it missed its chance to run?
# 
go_daily () {
    local kid
    for kid in `/bin/cat $configdir/kid.list | sort -u`; do

        /usr/bin/stat -c %y $basedir/time/$kid.ttl | /bin/grep -q $Cdate
        #reset ttl for next day
        if [ ! $? -eq 0 ]; then
            reset_time $kid
        fi
    done
    # %%% needs to be rethought
    #go_hourly
}


#
# Determine if allowed to use computer during this schedule
#
hourlyCheck () {
    local kid=$1
    local allowed=$2
    local min=1 #non zero value is all we need
    local schedule_result

    if [ -e $basedir/schedule/$kid ]; then

        #grab mins left
        [ -e $basedir/time/$kid.ttl ] && min=`/bin/cat $basedir/time/$kid.ttl`
        #lock account if out of minutes

        #%%% bug should return and not exit on 0
        if [ $min -le 0 ] ; then
            #/usr/bin/passwd $kid -l
            allowed=0
            return 0
        fi

        # Disable/Enable depending on if allowed during time of day
        [ "$WEEKEND" == "no" ] && schedule_result=`/bin/grep ^$HOUR $basedir/schedule/$kid | /usr/bin/awk '{ print $2 }'`
        [ "$WEEKEND" == "yes" ] && schedule_result=`/bin/grep ^$HOUR $basedir/schedule/$kid | /usr/bin/awk '{ print $3 }'`
        if [ "$schedule_result" == "y" ]; then
            allowed=1   # allowed to use computer
        else
            allowed=0   # not allowed to use computer
        fi

    fi


    return 0
}

go_hourly () {
    local kid
    local current
    local result
    if [ -s $configdir/kid.list ]; then
        for kid in `/bin/cat $configdir/kid.list | sort -u`; do
            if [ -e $basedir/schedule/$kid ]; then
                [ -e $basedir/time/$kid.ttl ] && current=`/bin/cat $basedir/time/$kid.ttl`
                # %%% if ttl has gone negative, we lock password file and exit????
                #[ $current -le 0 ] && /usr/bin/passwd $kid -l && exit 0
                [ $current -le 0 ] && exit 0
                [ "$WEEKEND" == "no" ] && result=`/bin/grep ^$HOUR $basedir/schedule/$kid | /usr/bin/awk '{ print $2 }'`
                [ "$WEEKEND" == "yes" ] && result=`/bin/grep ^$HOUR $basedir/schedule/$kid | /usr/bin/awk '{ print $3 }'`
                if [ "$result" == "y" ]; then
                    go_unlock_account $kid
                else
                    go_lock_account $kid

                    # should gnome-screensaver-command -l

                    # This method ( /usr/bin/users ) to determine who is logged in is a kludge.  It ignores locked screens (screensaver active) and switched user states.
                    /usr/bin/users | /bin/grep -q $kid
                    if [ $? -eq 0 ]; then
                        # %%% if this file exists, do no issue logout sequence
                        if [ ! -e ${SHUTDOWN_BASE}.${kid} ]; then
                            go_logout $kid 1
                        fi
                    fi
                fi
            fi
        done
    fi
}


go_recheck_logout () {
    local kid=$1
    local min
    local allowed
    local schedule_result

    # Check if user is still logged in
    /usr/bin/users | /bin/grep -q $kid
    if [ $? -ne 0 ]; then
        /bin/rm -rf ${SHUTDOWN_BASE}.${kid}
        go_clean_jobs $kid
        return 0
    fi

    # Recheck time and schedule
    min=0
    [ -e $basedir/time/$kid.ttl ] && min=`/bin/cat $basedir/time/$kid.ttl`

    allowed=1
    if [ -e $basedir/schedule/$kid ]; then
        local HOUR=`/bin/date +%H`
        local DOW=`/bin/date +%u`
        local WEEKEND="no"
        [ "$DOW" == "6" ] && WEEKEND="yes"
        [ "$DOW" == "7" ] && WEEKEND="yes"
        [ "$WEEKEND" == "no" ] && schedule_result=`/bin/grep ^$HOUR $basedir/schedule/$kid | /usr/bin/awk '{ print $2 }'`
        [ "$WEEKEND" == "yes" ] && schedule_result=`/bin/grep ^$HOUR $basedir/schedule/$kid | /usr/bin/awk '{ print $3 }'`
        [ "$schedule_result" != "y" ] && allowed=0
    fi

    # Cancel shutdown if time is sufficient and user is allowed
    if [ $min -gt 5 ] && [ $allowed -eq 1 ]; then
        /bin/rm -rf ${SHUTDOWN_BASE}.${kid}
        go_clean_jobs $kid
        return 0
    fi

    return 1
}

# Async logout for cron - schedules jobs via at and returns immediately
go_logout_async () {
    local kid=$1

    # only start this if they are logged in
    /usr/bin/users | /bin/grep -q $kid
    if [ $? -ne 0 ]; then
        return
    fi

    # schedule the shutdown if we haven't already
    if [ ! -e ${SHUTDOWN_BASE}.${kid} ]; then
        go_send $kid 5
        go_send $kid 4
        go_send $kid 3
        go_send $kid 2
        go_send $kid 1
        go_killall_async $kid
        /usr/bin/touch ${SHUTDOWN_BASE}.${kid}
    fi
}

# Sync logout for manual command - runs directly with sleep
go_logout_sync () {
    local kid=$1
    local time

    # only start this if they are logged in
    /usr/bin/users | /bin/grep -q $kid
    if [ $? -ne 0 ]; then
        return
    fi

    # Clean up old state and force new sequence
    if [ -e ${SHUTDOWN_BASE}.${kid} ]; then
        /bin/rm -rf ${SHUTDOWN_BASE}.${kid}
        go_clean_jobs $kid
    fi

    /usr/bin/touch ${SHUTDOWN_BASE}.${kid}

    for time in 5 4 3 2 1; do
        go_send_sync $kid $time

        if [ $time -gt 1 ]; then
            /bin/sleep 60
        fi
    done

    /bin/sleep 60

    go_killall $kid
}


play_sound () {
    local user=$1
    local TMPFILE=$2
    local SOUND_PLAYER=""
    local SOUND_FILE=""

    if [ -x /usr/bin/paplay ]; then
        SOUND_PLAYER="/usr/bin/paplay"
    elif [ -x /usr/bin/pw-play ]; then
        SOUND_PLAYER="/usr/bin/pw-play"
    elif [ -x /usr/bin/aplay ]; then
        SOUND_PLAYER="/usr/bin/aplay"
    fi

    if [ -f /usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga ]; then
        SOUND_FILE="/usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga"
    elif [ -f /usr/share/sounds/freedesktop/stereo/bell.oga ]; then
        SOUND_FILE="/usr/share/sounds/freedesktop/stereo/bell.oga"
    elif [ -f /usr/share/sounds/freedesktop/stereo/dialog-warning.oga ]; then
        SOUND_FILE="/usr/share/sounds/freedesktop/stereo/dialog-warning.oga"
    fi

    if [ -n "${SOUND_PLAYER}" ] && [ -n "${SOUND_FILE}" ]; then
        echo "/bin/su $user -c '${SOUND_PLAYER} ${SOUND_FILE} &' 2>/dev/null" >> $TMPFILE
    fi
}


# Creates the notification script, returns path in SEND_SCRIPT
# $1 = user, $2 = time, $3 = recheck (1=yes, 0=no)
create_send_script () {
    local user=$1
    local time=$2
    local recheck=$3
    local line=$((7-$time))
    local text=$((6-$time))
    SEND_SCRIPT="/tmp/kidtimer.send$time.bash.$user"

    /bin/rm -f $SEND_SCRIPT

    cat > $SEND_SCRIPT << 'EOF'
#!/bin/bash
user="@@USER@@"
text="@@TEXT@@"
line="@@LINE@@"
TMPFILE="@@TMPFILE@@"
recheck="@@RECHECK@@"
basedir="/usr/local/kidtimer"
LANG="${LANG:-en_US.UTF-8}"

# Recheck if logout is still needed
if [ "$recheck" -eq 1 ]; then
    /usr/local/bin/kidtimer recheck ${user}
    if [ $? -eq 0 ]; then
        /bin/rm -f $TMPFILE
        exit 0
    fi
fi

# Build message
if [ -e $basedir/locale/$LANG ]; then
    MSG="$user: $(/bin/sed -n "${line}p" $basedir/locale/$LANG)"
else
    MSG="$user's computer time will end in $text minutes."
fi

# Send notification to all displays
for (( display = 0 ; display < 10 ; display++ )); do
    /bin/su $user -c "DISPLAY=:$display /usr/bin/notify-send -i $basedir/icons/kidtimer-$text.png \"ALERT\" \"$MSG\"" 2>/dev/null
done

# Play sound
SOUND_PLAYER=""
SOUND_FILE=""

if [ -x /usr/bin/paplay ]; then
    SOUND_PLAYER="/usr/bin/paplay"
elif [ -x /usr/bin/pw-play ]; then
    SOUND_PLAYER="/usr/bin/pw-play"
elif [ -x /usr/bin/aplay ]; then
    SOUND_PLAYER="/usr/bin/aplay"
fi

if [ -f /usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga ]; then
    SOUND_FILE="/usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga"
elif [ -f /usr/share/sounds/freedesktop/stereo/bell.oga ]; then
    SOUND_FILE="/usr/share/sounds/freedesktop/stereo/bell.oga"
elif [ -f /usr/share/sounds/freedesktop/stereo/dialog-warning.oga ]; then
    SOUND_FILE="/usr/share/sounds/freedesktop/stereo/dialog-warning.oga"
fi

if [ -n "${SOUND_PLAYER}" ] && [ -n "${SOUND_FILE}" ]; then
    /bin/su $user -c "${SOUND_PLAYER} ${SOUND_FILE} &" 2>/dev/null
fi

/bin/rm -f $TMPFILE
EOF

    # Replace placeholders
    /bin/sed -i "s|@@USER@@|${user}|g" $SEND_SCRIPT
    /bin/sed -i "s|@@TEXT@@|${text}|g" $SEND_SCRIPT
    /bin/sed -i "s|@@LINE@@|${line}|g" $SEND_SCRIPT
    /bin/sed -i "s|@@TMPFILE@@|${SEND_SCRIPT}|g" $SEND_SCRIPT
    /bin/sed -i "s|@@RECHECK@@|${recheck}|g" $SEND_SCRIPT

    chmod +x $SEND_SCRIPT
}

# Async - schedules notification via at
go_send () {
    local user=$1
    local time=$2

    create_send_script $user $time 1
    echo "/bin/bash $SEND_SCRIPT" | /usr/bin/at now + $time minutes
    # Note you need the file /var/spool/cron/atjobs/.SEQ owned by daemon:daemon for at to work properly!!!
}

# Sync - executes notification immediately
go_send_sync () {
    local user=$1
    local time=$2

    create_send_script $user $time 0
    /bin/bash $SEND_SCRIPT
}


# Creates the kill script, returns path in KILL_SCRIPT
# $1 = user, $2 = recheck (1=yes, 0=no)
create_kill_script () {
    local user=$1
    local recheck=$2
    KILL_SCRIPT="${KILLALL_BASE}.${user}"

    /bin/rm -f $KILL_SCRIPT

    cat > $KILL_SCRIPT << 'EOF'
#!/bin/bash
user="@@USER@@"
recheck="@@RECHECK@@"
SHUTDOWN_BASE="/var/run/kidtimer.shutdown"
KILLALL_BASE="/var/run/kidtimer.killall"
KILL_SCRIPT="@@KILL_SCRIPT@@"

# Recheck if logout is still needed
if [ "$recheck" -eq 1 ]; then
    /usr/local/bin/kidtimer recheck ${user}
    if [ $? -eq 0 ]; then
        /bin/rm -f $KILL_SCRIPT
        exit 0
    fi
fi

# Lock the account immediately to prevent re-login
/usr/bin/passwd ${user} -l

# Lock all sessions for the user
for session in $(/usr/bin/loginctl list-sessions --no-legend | /usr/bin/awk '{print $1}'); do
    # Get the user's D-Bus session address
    dbus_addr=$(ps e -u $user | grep -o 'DBUS_SESSION_BUS_ADDRESS=[^ ]*' | head -1)


    session_user=$(/usr/bin/loginctl show-session $session -p Name --value)
    if [ "$session_user" == "$user" ]; then
        /usr/bin/loginctl lock-session $session 2>/dev/null
    fi

    # Lock the session via D-Bus
    if [ -n "$dbus_addr" ]; then
        /bin/su - $user -c "$dbus_addr dbus-send --session --type=method_call --dest=org.gnome.ScreenSaver \
            /org/gnome/ScreenSaver org.gnome.ScreenSaver.Lock" 2>/dev/null
    fi
done

# Clean up
/bin/rm -rf ${SHUTDOWN_BASE}.${user}
/bin/rm -f ${KILLALL_BASE}.${user}

# Hibernate
/usr/sbin/pm-hibernate
EOF

    # Replace placeholders
    /bin/sed -i "s|@@USER@@|${user}|g" $KILL_SCRIPT
    /bin/sed -i "s|@@RECHECK@@|${recheck}|g" $KILL_SCRIPT
    /bin/sed -i "s|@@KILL_SCRIPT@@|${KILL_SCRIPT}|g" $KILL_SCRIPT

    chmod +x $KILL_SCRIPT
}

# Sync - executes kill immediately
go_killall () {
    local user=$1

    create_kill_script $user 0
    /bin/bash $KILL_SCRIPT
}

# Async - schedules kill via at
go_killall_async () {
    local user=$1

    create_kill_script $user 1
    echo "/bin/bash $KILL_SCRIPT" | /usr/bin/at now + 6 minutes
}


go_echo_error () {
    echo "`/bin/sed -n '12p' /usr/local/kidtimer/locale/$LANG`"
}


go_echo_done () {
    echo "`/bin/sed -n '13p' /usr/local/kidtimer/locale/$LANG`"
}

reset_time () {
    local KID=$1

    # make sure this kid is in the list to begin with
    grep -q $KID $configdir/kid.list
    if [ $? -eq 0 ]; then
        get_ttl_time $KID > $basedir/time/$KID.ttl
        go_unlock_account $KID
        go_clean_jobs $KID
        go_echo_done
    fi
}

go_addtime () {
    local user=$KID
    local addtime=$Time
    local current

    grep -q $user $configdir/kid.list
    if [ $? -eq 0 ]; then
        if [ "$addtime" == "reset" ]; then
            get_ttl_time $user > $basedir/time/$user.ttl
            go_echo_done
            exit 0
        elif [ "$addtime" == "" ]; then
            go_echo_error
            #english: Syntax: addtime <user> <minutes|reset>
            echo "`/bin/sed -n '22p' /usr/local/kidtimer/locale/$LANG`"
            exit 1
        else
            current=`/bin/cat $basedir/time/$KID.ttl`
            current=$((current + Time))
            echo $current > $basedir/time/$KID.ttl
            get_time
        fi
        go_unlock_account $KID
        go_clean_jobs $KID
    else
        go_echo_error
        #english: User not setup.
        echo "`/bin/sed -n '19p' /usr/local/kidtimer/locale/$LANG`"
        exit 1
    fi
}


get_time () {
    if [ -e $basedir/time/$KID.ttl ]; then
        cat $basedir/time/$KID.ttl
    else
        echo
        #english: User not setup.
        echo "`/bin/sed -n '19p' /usr/local/kidtimer/locale/$LANG`"
        echo
    fi
}


go_tui () {
    local choice

    go_command_list
    echo -n "Choose: "; read choice
    case "$choice" in
    1) go_setup_user
        ;;
    2) go_modify_user
        ;;
    3) go_remove_user
        ;;
    4) go_list_users
        ;;
    5) exit 0
        ;;
    esac
    go_tui
}


go_command_list () {
    echo
    echo "1) "`/bin/sed -n '7p' /usr/local/kidtimer/locale/$LANG`
    echo "2) "`/bin/sed -n '8p' /usr/local/kidtimer/locale/$LANG`
    echo "3) "`/bin/sed -n '9p' /usr/local/kidtimer/locale/$LANG`
    echo "4) "`/bin/sed -n '10p' /usr/local/kidtimer/locale/$LANG`
    echo "5) "`/bin/sed -n '11p' /usr/local/kidtimer/locale/$LANG`
    echo
}


go_list_users () {
    echo
    #english: Users configured for kidtimer:
    echo "`/bin/sed -n '14p' /usr/local/kidtimer/locale/$LANG`"
    if [ -s $configdir/kid.list ]; then
        /bin/cat $configdir/kid.list
    else
        #english: No configured users.
        echo "`/bin/sed -n '15p' /usr/local/kidtimer/locale/$LANG`"
        echo
    fi
}

go_setup_user () {
    local user
    local modify

    echo
    #english: Username:
    echo -n "`/bin/sed -n '16p' /usr/local/kidtimer/locale/$LANG` "; read user
    /usr/bin/id $user > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        /bin/cp $basedir/schedule/blank $basedir/schedule/$user
        get_ttl_time $user > $basedir/time/$user.ttl
        echo $user >> $configdir/kid.list
        go_echo_done
        echo
        #english: Modify limits now ?(y/n):
        echo -n "`/bin/sed -n '17p' /usr/local/kidtimer/locale/$LANG`"; read modify
        if [ "$modify" == "y" ]; then
            if [ -e /usr/bin/nano ]; then
                /usr/bin/nano $basedir/schedule/$user
                get_ttl_time $user > $basedir/time/$user.ttl
                go_echo_done
            else
                /usr/bin/vi $basedir/schedule/$user
                get_ttl_time $user > $basedir/time/$user.ttl
                go_echo_done
            fi
        fi
    else
        go_echo_error
        #english: User does not exist. Please create user using the useradd command first.
        echo "`/bin/sed -n '18p' /usr/local/kidtimer/locale/$LANG`"
    fi
}


go_modify_user () {
    local user

    echo
    #english: Username:
    echo -n "`/bin/sed -n '16p' /usr/local/kidtimer/locale/$LANG` "; read user
    grep -q ^$user $configdir/kid.list
    if [ $? -eq 0 ]; then
        if [ -e /usr/bin/nano ]; then
            /usr/bin/nano $basedir/schedule/$user
            go_echo_done
        else
            /usr/bin/vi $basedir/schedule/$user
            go_echo_done
        fi
    else
        go_echo_error
        #english: User not setup.
        echo "`/bin/sed -n '19p' /usr/local/kidtimer/locale/$LANG`"
        echo
    fi
}


go_remove_user () {
    local user

    echo
    #english: Username:
    echo -n "`/bin/sed -n '16p' /usr/local/kidtimer/locale/$LANG` "; read user
    grep -q ^$user $configdir/kid.list
    if [ $? -eq 0 ]; then
        /bin/grep -v ^$user $configdir/kid.list > /tmp/kidtimer.tmp
        /bin/cat /tmp/kidtimer.tmp > $configdir/kid.list
        go_echo_done
    else
        go_echo_error
        #english: User not setup.
        echo "`/bin/sed -n '19p' /usr/local/kidtimer/locale/$LANG`"
        echo
    fi
}


go_help () {
    echo
    echo "Commands:"
    echo "--------------------------------------------------------------------------------"
    echo "addtime <user> <minutes> ... Increases allowed time for the day."
    echo "gettime <user> ... Prints remaining time for the day."
    echo "reset <user> ... Reset time for the day."
    echo "logout <user> ... Starts logout sequence for user."
    echo "kill <user> ... Kills all user processes and hibernates computer."
    echo "hourly ... Enables/disables user access based on the schedule."
    echo "daily ... Resets time for the new day."
    echo "info ... Gather local configurations to troubleshoot issues."
    echo "help ... This list."
    echo "--------------------------------------------------------------------------------"
}

check_dependencies () {
    local pkg1=""
    local pkg2=""
    local pkg3=""
    local pstatus="0"

    #at
    /usr/bin/dpkg -s at >/dev/null 2>/dev/null
    if [ ! $? -eq 0 ]; then
        pkg1="at"
        pstatus=1
    fi
    #libnotify-bin
    /usr/bin/dpkg -s libnotify-bin >/dev/null 2>/dev/null
    if [ ! $? -eq 0 ]; then
        pkg2="libnotify-bin"
        pstatus=1
    fi
    #bsdutils
    /usr/bin/dpkg -s bsdutils >/dev/null 2>/dev/null
    if [ ! $? -eq 0 ]; then
        pkg3="bsdutils"
        pstatus=1
    fi
    if [ "$pstatus" == "1" ]; then
        echo
        #english: Error. Missing package dependencies.
        echo "`/bin/sed -n '20p' /usr/local/kidtimer/locale/$LANG`"
        #english: Please install using the following line;
        echo "`/bin/sed -n '21p' /usr/local/kidtimer/locale/$LANG`"
        echo "sudo apt-get install "$pkg1" "$pkg2" "$pkg3
        exit 1
    fi
}

###################### Code ####################
################################################

if [ $TUI -eq 1 ]; then
    check_dependencies
    go_tui
fi

case "$COMMAND" in
addtime) go_addtime
        ;;
reset) reset_time $KID
        ;;
gettime) get_time
        ;;
logout) go_logout_sync $KID
        ;;
kill) go_killall $KID
        ;;
recheck) go_recheck_logout $KID
        exit $?
        ;;
hourly) go_hourly
        ;;
daily) go_daily
        ;;
check) go_check
        ;;
info) get_info
        ;;
-h) go_help
        ;;
help) go_help
        ;;
esac
exit 0
